services:
  - type: web
    name: luxortum
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 8080